import type { AdminClient } from './orgs'
import { ensureDemoChannels, isMissingTableError } from './orgs'

type SampleProduct = {
  slug: string
  name: string
  description: string
  priceCents: number
  costCents: number
  status: 'ready' | 'draft' | 'needs_fix'
  visibility: 'visible' | 'hidden'
  conceptImages: string[]
  channels: Array<{ kind: string; status: 'connected' | 'pending' | 'disconnected' }>
}

const SAMPLE_PRODUCTS: SampleProduct[] = [
  {
    slug: 'orbital-desk-rocket',
    name: 'Orbital Desk Rocket',
    description: 'Autogenerated copy: Compact rocket-themed desk sculpture with cable passthrough and tool-free assembly.',
    priceCents: 2800,
    costCents: 1250,
    status: 'ready',
    visibility: 'visible',
    conceptImages: [
      'https://dummyimage.com/512x512/06080b/2ee6d6&text=Front',
      'https://dummyimage.com/512x512/06080b/ffffff&text=Side',
    ],
    channels: [
      { kind: 'shopify', status: 'connected' },
      { kind: 'etsy', status: 'pending' },
    ],
  },
  {
    slug: 'flux-cable-nest',
    name: 'Flux Cable Nest',
    description: 'AI draft: Modular cable management tray with hidden clips and heat-set inserts (edit to add material specs).',
    priceCents: 1900,
    costCents: 980,
    status: 'draft',
    visibility: 'hidden',
    conceptImages: [
      'https://dummyimage.com/512x512/06080b/8fd2ca&text=Front',
      'https://dummyimage.com/512x512/06080b/8fd2ca&text=Back',
    ],
    channels: [
      { kind: 'shopify', status: 'connected' },
    ],
  },
  {
    slug: 'arcadia-planter-pedestal',
    name: 'Arcadia Planter Pedestal',
    description: 'Human edit required: eco PLA, 180 mm tall, includes water reservoir. Fill in finish options and lead times.',
    priceCents: 3800,
    costCents: 1725,
    status: 'needs_fix',
    visibility: 'hidden',
    conceptImages: [
      'https://dummyimage.com/512x512/06080b/ffffff&text=Front',
    ],
    channels: [
      { kind: 'shopify', status: 'disconnected' },
      { kind: 'tiktok', status: 'disconnected' },
    ],
  },
]

export async function ensureSampleProducts(client: AdminClient, orgId: string) {
  const existing = await client
    .from('products')
    .select('id', { count: 'exact', head: true })
    .eq('org_id', orgId)

  if (existing.error) {
    if (isMissingTableError(existing.error, 'products')) {
      console.warn('[ensureSampleProducts] products table missing; skipping sample insert')
      return
    }
    throw existing.error
  }

  if ((existing.count ?? 0) > 0) {
    return
  }

  await ensureDemoChannels(client, orgId)

  const channelResult = await client
    .from('channel_accounts')
    .select('id, kind')
    .eq('org_id', orgId)

  if (channelResult.error) {
    if (isMissingTableError(channelResult.error, 'channel_accounts')) {
      console.warn('[ensureSampleProducts] channel_accounts table missing; skipping sample products')
      return
    }
    throw channelResult.error
  }
  const channelMap = new Map<string, string>()
  for (const row of channelResult.data ?? []) {
    channelMap.set(row.kind, row.id)
  }

  for (const sample of SAMPLE_PRODUCTS) {
    const productInsert = await client
      .from('products')
      .insert({
        org_id: orgId,
        status: sample.status,
        visibility: sample.visibility,
      })
      .select('id, created_at')
      .single()
    if (productInsert.error || !productInsert.data?.id) {
      if (isMissingTableError(productInsert.error, 'products')) {
        console.warn('[ensureSampleProducts] products table missing on insert; skipping remaining samples')
        return
      }
      throw productInsert.error ?? new Error('product insert failed')
    }
    const productId = productInsert.data.id as string

    const versionNumber = 1
    const versionInsert = await client
      .from('product_versions')
      .insert({
        product_id: productId,
        version: versionNumber,
        name: sample.name,
        description: sample.description,
        price_cents: sample.priceCents,
        cost_cents: sample.costCents,
        margin_cents: sample.priceCents - sample.costCents,
        info_json: { slug: sample.slug },
      })
      .select('id')
      .single()
    if (versionInsert.error || !versionInsert.data?.id) {
      if (isMissingTableError(versionInsert.error, 'product_versions')) {
        console.warn('[ensureSampleProducts] product_versions table missing; aborting sample insert')
        return
      }
      throw versionInsert.error ?? new Error('product version insert failed')
    }
    const versionId = versionInsert.data.id as string

    const updateProduct = await client
      .from('products')
      .update({ current_version_id: versionId })
      .eq('id', productId)
    if (updateProduct.error) {
      if (isMissingTableError(updateProduct.error, 'products')) {
        console.warn('[ensureSampleProducts] products table missing during update; continuing in demo mode')
      } else {
        throw updateProduct.error
      }
    }

    if (sample.conceptImages.length > 0) {
      const assetRows = sample.conceptImages.map((url, idx) => ({
        product_id: productId,
        version: versionNumber,
        kind: idx === 0 ? 'thumbnail' : 'concept_image',
        storage_path: url,
        meta_json: { url, sample: true },
      }))
      const { error: assetErr } = await client.from('product_assets').insert(assetRows)
      if (assetErr) {
        if (isMissingTableError(assetErr, 'product_assets')) {
          console.warn('[ensureSampleProducts] product_assets table missing; skipping concept images')
        } else {
          throw assetErr
        }
      }
    }

    const metricsInsert = await client
      .from('product_metrics')
      .upsert({
        product_id: productId,
        print_success_rate: 0.95,
        avg_print_time_seconds: 3600,
        avg_material_grams: 45,
      })
    if (metricsInsert.error) {
      if (isMissingTableError(metricsInsert.error, 'product_metrics')) {
        console.warn('[ensureSampleProducts] product_metrics table missing; skipping metrics seed')
      } else {
        throw metricsInsert.error
      }
    }

    for (const channel of sample.channels) {
      const accountId = channelMap.get(channel.kind)
      if (!accountId) continue
      const { error } = await client.from('product_channel_state').insert({
        org_id: orgId,
        product_id: productId,
        product_version_id: versionId,
        channel_account_id: accountId,
        status: channel.status === 'connected' ? 'published' : channel.status === 'pending' ? 'syncing' : 'not_synced',
      })
      if (error) {
        if (isMissingTableError(error, 'product_channel_state')) {
          console.warn('[ensureSampleProducts] product_channel_state table missing; skipping channel status seed')
        } else {
          throw error
        }
      }
    }
  }
}
