"use client"

import { useEffect } from 'react'
import dynamic from 'next/dynamic'

const Stage = dynamic(() => import('./Stage'), { ssr: false })

export type UploadDraftViewModel = {
  id: string
  name: string
  description: string
  priceCents: number
  costCents: number
  status: 'draft' | 'ready' | 'needs_fix'
  visibility: 'visible' | 'hidden'
  objectUrl: string
  fileName: string
  ext: string
  aiSummary?: string | null
}

type UploadProductModalProps = {
  open: boolean
  draft: UploadDraftViewModel | null
  saving: boolean
  error: string | null
  onClose: () => void
  onSave: () => void
  onDiscard: () => void
  onChange: (update: Partial<Pick<UploadDraftViewModel, 'name' | 'description' | 'priceCents' | 'costCents'>>) => void
}

function centsToDollars(cents: number): string {
  return (Math.round(cents) / 100).toFixed(2)
}

function dollarsToCents(value: string, fallback: number): number {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return fallback
  return Math.max(0, Math.round(numeric * 100))
}

export default function UploadProductModal({
  open,
  draft,
  saving,
  error,
  onClose,
  onSave,
  onDiscard,
  onChange,
}: UploadProductModalProps) {
  useEffect(() => {
    if (!open) return
    const original = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => {
      document.body.style.overflow = original
    }
  }, [open])

  if (!open || !draft) return null

  const priceDisplay = centsToDollars(draft.priceCents)
  const costDisplay = centsToDollars(draft.costCents)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" aria-hidden onClick={saving ? undefined : onClose} />
      <div className="panel relative z-10 flex max-h-[calc(100vh-2rem)] w-[min(1040px,calc(100vw-2rem))] flex-col overflow-hidden">
        <header className="flex items-center justify-between border-b border-white/10 px-6 py-4">
          <div>
            <div className="text-xs uppercase tracking-[0.28em] text-teal/70">New product draft</div>
            <h2 className="text-xl font-semibold text-white">Review autogenerated details</h2>
          </div>
          <button
            type="button"
            onClick={onDiscard}
            className="text-sm text-textMuted transition hover:text-warning"
            disabled={saving}
          >
            Discard
          </button>
        </header>
        <div className="flex flex-1 flex-col gap-6 overflow-auto px-6 py-6 lg:flex-row">
          <div className="flex flex-1 flex-col gap-3">
            <div className="relative aspect-square w-full overflow-hidden rounded-xl border border-white/10 bg-black/40">
              {draft.objectUrl ? (
                <Stage localPreview={{ url: draft.objectUrl, ext: draft.ext }} />
              ) : (
                <div className="flex h-full w-full items-center justify-center text-sm text-textMuted">
                  Preparing preview…
                </div>
              )}
            </div>
            <div className="rounded-lg border border-white/10 bg-white/5 px-3 py-3 text-xs leading-relaxed text-textMuted">
              We generated a working title and description from the uploaded model name. Feel free to tweak them before saving to your catalog.
            </div>
          </div>
          <div className="flex w-full flex-col gap-4 lg:max-w-[360px]">
            <label className="flex flex-col gap-2 text-sm">
              <span className="text-xs uppercase tracking-[0.26em] text-textMuted">Title</span>
              <input
                type="text"
                value={draft.name}
                onChange={(event) => onChange({ name: event.target.value })}
                className="w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-sm text-white placeholder:text-textMuted focus:border-teal/60 focus:outline-none"
                placeholder="Give this product a name"
                disabled={saving}
              />
            </label>
            <label className="flex flex-col gap-2 text-sm">
              <span className="text-xs uppercase tracking-[0.26em] text-textMuted">Description</span>
              <textarea
                value={draft.description}
                onChange={(event) => onChange({ description: event.target.value })}
                className="h-32 w-full resize-none rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-sm leading-relaxed text-textPrimary focus:border-teal/60 focus:outline-none"
                placeholder="Describe materials, sizing, and what makes this print special"
                disabled={saving}
              />
            </label>
            <div className="grid grid-cols-2 gap-3">
              <label className="flex flex-col gap-2 text-sm">
                <span className="text-xs uppercase tracking-[0.26em] text-textMuted">Price (USD)</span>
                <input
                  type="number"
                  step="0.01"
                  inputMode="decimal"
                  value={priceDisplay}
                  onChange={(event) => onChange({ priceCents: dollarsToCents(event.target.value, draft.priceCents) })}
                  className="w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-sm text-white placeholder:text-textMuted focus:border-teal/60 focus:outline-none"
                  disabled={saving}
                />
              </label>
              <label className="flex flex-col gap-2 text-sm">
                <span className="text-xs uppercase tracking-[0.26em] text-textMuted">Estimated cost</span>
                <input
                  type="number"
                  step="0.01"
                  inputMode="decimal"
                  value={costDisplay}
                  onChange={(event) => onChange({ costCents: dollarsToCents(event.target.value, draft.costCents) })}
                  className="w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-sm text-white placeholder:text-textMuted focus:border-teal/60 focus:outline-none"
                  disabled={saving}
                />
              </label>
            </div>
            <div className="rounded-lg border border-white/10 bg-white/5 px-3 py-3 text-xs leading-relaxed text-textMuted">
              <div className="font-medium text-textPrimary">Upload summary</div>
              <div className="mt-2 grid grid-cols-2 gap-y-1 text-[11px] uppercase tracking-[0.18em] text-textMuted/70">
                <span>Filename</span>
                <span className="truncate text-right normal-case tracking-normal text-textPrimary/80">{draft.fileName}</span>
                <span>Format</span>
                <span className="text-right text-textPrimary/80">.{draft.ext}</span>
                <span>Status</span>
                <span className="text-right text-teal">Ready to import</span>
              </div>
            </div>
          </div>
        </div>
        {error && <div className="px-6 pb-2 text-sm text-warning">{error}</div>}
        <footer className="flex items-center justify-between border-t border-white/10 px-6 py-4">
          <button
            type="button"
            className="rounded-lg border border-white/15 px-4 py-2 text-sm text-textMuted transition hover:border-white/30 hover:text-white"
            onClick={onDiscard}
            disabled={saving}
          >
            Cancel
          </button>
          <div className="flex items-center gap-3">
            <div className="text-xs uppercase tracking-[0.28em] text-textMuted/70">Step 1 · Add to catalog</div>
            <button
              type="button"
              onClick={onSave}
              disabled={saving}
              className="rounded-lg bg-teal px-4 py-2 text-sm font-medium text-black shadow-[0_8px_18px_rgba(46,230,214,0.25)] transition hover:brightness-110 disabled:opacity-60"
            >
              {saving ? 'Saving…' : 'Save product'}
            </button>
          </div>
        </footer>
      </div>
    </div>
  )
}
