"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import LeftRail from '@/components/LeftRail'
import HoloCheckbox, { type CheckedState } from '@/components/HoloCheckbox'
import UploadProductModal, { type UploadDraftViewModel } from '@/components/UploadProductModal'
import { supabaseBrowser } from '@/lib/supabaseClient'

type ChannelStatus = 'connected' | 'disconnected' | 'pending'

type Product = {
  id: string
  name: string
  description: string
  autogenerated: boolean
  priceCents: number
  costCents: number
  thumbnailUrl: string
  status: 'repairing' | 'ready' | 'needs_fix' | 'draft'
  updatedAt: string
  channels: Array<{ name: string; status: ChannelStatus }>
  inventoryEnabled: boolean
  conceptImages: string[]
}

type ApiProduct = {
  id: string
  name: string
  description: string
  priceCents: number
  costCents: number
  marginCents: number
  status: string
  visibility: string
  updatedAt: string
  channels: Array<{
    status: string
    account?: { id: string; kind: string; displayName: string; status: string } | null
  }>
  conceptImages: Array<{ url: string; kind: string }>
}

const DEMO_USER_ID = process.env.NEXT_PUBLIC_DEMO_USER_ID ?? '00000000-0000-4000-8000-000000000001'

const ACCEPTED_EXTENSIONS = ['stl', 'obj', 'glb', 'gltf'] as const
type AcceptedExtension = (typeof ACCEPTED_EXTENSIONS)[number]

type DraftProductState = {
  id: string
  file: File
  objectUrl: string
  ext: AcceptedExtension
  name: string
  description: string
  priceCents: number
  costCents: number
  status: 'draft' | 'ready' | 'needs_fix'
  visibility: 'visible' | 'hidden'
}

function formatCurrency(cents: number) {
  return Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100)
}

function formatDate(iso: string) {
  return Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date(iso))
}

function channelChip(status: ChannelStatus) {
  if (status === 'connected') return 'bg-teal/20 text-teal'
  if (status === 'pending') return 'bg-warning/20 text-warning'
  return 'bg-white/10 text-textMuted'
}

function channelColor(name: string) {
  const map: Record<string, string> = {
    Shopify: 'bg-[#96bf48]/20 text-[#96bf48]',
    Etsy: 'bg-[#f45800]/20 text-[#f45800]',
    TikTok: 'bg-[#69c9d0]/20 text-[#69c9d0]',
  }
  return map[name] ?? 'bg-white/10 text-textPrimary'
}

function channelInitials(name: string) {
  return name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .slice(0, 2)
    .toUpperCase()
}

function statusDot(status: ChannelStatus) {
  if (status === 'connected') return 'bg-teal'
  if (status === 'pending') return 'bg-warning'
  return 'bg-white/40'
}

function inferExtension(fileName: string): AcceptedExtension | null {
  const ext = fileName.split('.').pop()?.toLowerCase()
  if (!ext) return null
  return ACCEPTED_EXTENSIONS.includes(ext as AcceptedExtension) ? (ext as AcceptedExtension) : null
}

function generateTitleFromFile(fileName: string): string {
  const base = fileName.replace(/\.[^.]+$/, '')
  const cleaned = base
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  if (!cleaned) return 'Untitled print'
  return cleaned
    .split(' ')
    .map((word) => (word.length === 0 ? word : word[0].toUpperCase() + word.slice(1)))
    .join(' ')
    .slice(0, 120)
}

function generateDescriptionFromTitle(title: string): string {
  const trimmed = title.trim() || 'this model'
  return `${trimmed} — AI draft: add finish options, sizing notes, and print settings before publishing.`
}

function defaultPriceCents(): number {
  return 2800
}

function defaultCostCents(): number {
  return 1250
}

function mapChannelStatus(channel: ApiProduct['channels'][number]): { name: string; status: ChannelStatus } {
  const name = channel.account?.displayName ?? channel.account?.kind ?? 'Channel'
  const raw = `${channel.account?.status ?? channel.status}`.toLowerCase()
  if (raw.includes('connect')) return { name, status: 'connected' }
  if (raw.includes('pending') || raw.includes('sync')) return { name, status: 'pending' }
  return { name, status: 'disconnected' }
}

function mapApiProduct(api: ApiProduct): Product {
  const thumbnail = api.conceptImages.find((c) => c.kind === 'thumbnail')?.url ?? api.conceptImages[0]?.url ?? ''
  return {
    id: api.id,
    name: api.name,
    description: api.description,
    autogenerated: false,
    priceCents: api.priceCents,
    costCents: api.costCents,
    thumbnailUrl: thumbnail,
    status: (['repairing', 'ready', 'needs_fix', 'draft'].includes(api.status) ? api.status : 'draft') as Product['status'],
    updatedAt: api.updatedAt,
    channels: (api.channels ?? []).map(mapChannelStatus),
    inventoryEnabled: api.visibility === 'visible',
    conceptImages: (api.conceptImages ?? []).map((c) => c.url),
  }
}

export default function StorePage() {
  const [userId, setUserId] = useState<string | null>(null)
  const [products, setProducts] = useState<Product[]>([])
  const [selectedProductId, setSelectedProductId] = useState<string | null>(null)
  const showOperator = typeof process !== 'undefined' && Boolean(process.env.NEXT_PUBLIC_SHOW_OPERATOR)
  const [previewIndexByProduct, setPreviewIndexByProduct] = useState<Record<string, number>>({})
  const [selectedProductIds, setSelectedProductIds] = useState<Set<string>>(new Set())
  const [isDragging, setIsDragging] = useState(false)
  const [loading, setLoading] = useState(false)
  const [savingProductId, setSavingProductId] = useState<string | null>(null)
  const [draftQueue, setDraftQueue] = useState<DraftProductState[]>([])
  const [draftModalOpen, setDraftModalOpen] = useState(false)
  const [draftSaving, setDraftSaving] = useState(false)
  const [draftError, setDraftError] = useState<string | null>(null)
  const draftObjectUrlsRef = useRef<Set<string>>(new Set())

  const activeDraft = draftQueue.length > 0 ? draftQueue[0] : null

  const activeDraftViewModel: UploadDraftViewModel | null = useMemo(() => {
    if (!activeDraft) return null
    return {
      id: activeDraft.id,
      name: activeDraft.name,
      description: activeDraft.description,
      priceCents: activeDraft.priceCents,
      costCents: activeDraft.costCents,
      status: activeDraft.status,
      visibility: activeDraft.visibility,
      objectUrl: activeDraft.objectUrl,
      fileName: activeDraft.file.name,
      ext: activeDraft.ext,
      aiSummary: null,
    }
  }, [activeDraft])

  function createDraftFromFile(file: File): DraftProductState | null {
    const ext = inferExtension(file.name)
    if (!ext) return null
    const id = typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`
    const objectUrl = URL.createObjectURL(file)
    draftObjectUrlsRef.current.add(objectUrl)
    return {
      id,
      file,
      objectUrl,
      ext,
      name: generateTitleFromFile(file.name),
      description: generateDescriptionFromTitle(generateTitleFromFile(file.name)),
      priceCents: defaultPriceCents(),
      costCents: defaultCostCents(),
      status: 'draft',
      visibility: 'hidden',
    }
  }

  useEffect(() => {
    let active = true
    ;(async () => {
      try {
        const { data } = await supabaseBrowser.auth.getUser()
        if (!active) return
        if (data?.user?.id) setUserId(data.user.id)
        else setUserId(DEMO_USER_ID)
      } catch {
        if (active) setUserId(DEMO_USER_ID)
      }
    })()
    return () => {
      active = false
    }
  }, [])

  useEffect(() => {
    const trackedUrls = draftObjectUrlsRef.current
    return () => {
      trackedUrls.forEach((url) => {
        if (url.startsWith('blob:')) {
          try { URL.revokeObjectURL(url) } catch {}
        }
      })
      trackedUrls.clear()
    }
  }, [])

  useEffect(() => {
    if (!draftError || draftModalOpen) return
    const timeout = window.setTimeout(() => setDraftError(null), 4000)
    return () => window.clearTimeout(timeout)
  }, [draftError, draftModalOpen])

  const handleFiles = useCallback((files: FileList | File[]) => {
    const arr = Array.from(files)
    const validDrafts: DraftProductState[] = []
    arr.forEach((file) => {
      const draft = createDraftFromFile(file)
      if (draft) validDrafts.push(draft)
    })
    if (validDrafts.length === 0) {
      setDraftError('Only STL, OBJ, GLB, or GLTF files are supported right now.')
      return
    }
    setDraftQueue((prev) => [...prev, ...validDrafts])
    setDraftModalOpen(true)
    setDraftError(null)
  }, [])

  const updateDraft = useCallback((id: string, updates: Partial<DraftProductState>) => {
    setDraftQueue((prev) =>
      prev.map((draft) => (draft.id === id ? { ...draft, ...updates } : draft)),
    )
  }, [])

  const discardDraft = useCallback((id?: string) => {
    let shouldClose = false
    setDraftQueue((prev) => {
      const targetId = id ?? (prev[0]?.id ?? null)
      if (!targetId) return prev
      const next = prev.filter((draft) => {
        if (draft.id === targetId) {
          if (draft.objectUrl.startsWith('blob:')) {
            try { URL.revokeObjectURL(draft.objectUrl) } catch {}
          }
          draftObjectUrlsRef.current.delete(draft.objectUrl)
          return false
        }
        return true
      })
      if (next.length === 0) shouldClose = true
      return next
    })
    if (shouldClose) setDraftModalOpen(false)
    setDraftError(null)
  }, [])

  const handleDraftModalClose = useCallback(() => {
    if (activeDraft) {
      discardDraft(activeDraft.id)
    } else {
      setDraftModalOpen(false)
    }
  }, [activeDraft, discardDraft])

  const handleDraftChange = useCallback(
    (update: Partial<Pick<DraftProductState, 'name' | 'description' | 'priceCents' | 'costCents'>>) => {
      if (!activeDraft) return
      updateDraft(activeDraft.id, update)
    },
    [activeDraft, updateDraft],
  )

  const selectedProduct = useMemo(
    () => products.find((p) => p.id === selectedProductId) ?? null,
    [products, selectedProductId],
  )
  const previewImages = selectedProduct?.conceptImages ?? []
  const storedPreviewIndex = selectedProduct ? previewIndexByProduct[selectedProduct.id] ?? 0 : 0
  const safePreviewIndex = previewImages.length ? Math.min(Math.max(storedPreviewIndex, 0), previewImages.length - 1) : 0
  const previewImageUrl = previewImages[safePreviewIndex] ?? null

  const loadProducts = useCallback(async (options?: { selectId?: string }) => {
    if (!userId) return
    setLoading(true)
    try {
      const res = await fetch(`/api/store/products?user_id=${userId}`, { cache: 'no-store' })
      if (!res.ok) throw new Error(`status ${res.status}`)
      const data = await res.json()
      const mapped: Product[] = (data.products ?? []).map(mapApiProduct)
      setProducts(mapped)
      if (options?.selectId) {
        setSelectedProductId(options.selectId)
      } else if (!selectedProductId && mapped.length > 0) {
        setSelectedProductId(mapped[0].id)
      } else if (selectedProductId && !mapped.some((p) => p.id === selectedProductId) && mapped.length > 0) {
        setSelectedProductId(mapped[0].id)
      }
    } catch (error) {
      console.error('[store] load products failed', error)
    } finally {
      setLoading(false)
    }
  }, [selectedProductId, userId])

  useEffect(() => {
    void loadProducts()
  }, [loadProducts])

  function updateProduct(id: string, updater: (p: Product) => Product) {
    setProducts((prev) => prev.map((p) => (p.id === id ? updater(p) : p)))
  }

  const createProductFromDraft = useCallback(
    async (draft: DraftProductState) => {
      if (!userId) return
      setDraftSaving(true)
      setDraftError(null)
      try {
        const formData = new FormData()
        formData.append('user_id', userId)
        formData.append('file', draft.file)
        formData.append('name', draft.name)
        formData.append('description', draft.description)
        formData.append('priceCents', String(draft.priceCents))
        formData.append('costCents', String(draft.costCents))
        formData.append('status', draft.status)
        formData.append('visibility', draft.visibility)
        const res = await fetch('/api/store/products', {
          method: 'POST',
          body: formData,
        })
        if (!res.ok) throw new Error(`create ${res.status}`)
        const data = await res.json().catch(() => null)
        const newId: string | undefined = data?.product?.id
        await loadProducts({ selectId: newId })
        discardDraft(draft.id)
        if (newId) {
          setSelectedProductId(newId)
        }
      } catch (error) {
        console.error('[store] create product failed', error)
        setDraftError('Could not save this product. Please try again.')
      } finally {
        setDraftSaving(false)
      }
    },
    [discardDraft, loadProducts, userId],
  )

  const handleDraftSave = useCallback(() => {
    if (!activeDraft) return
    void createProductFromDraft(activeDraft)
  }, [activeDraft, createProductFromDraft])

  async function persistProduct(product: Product) {
    if (!userId) return
    setSavingProductId(product.id)
    try {
      const res = await fetch(`/api/store/products/${product.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id: userId,
          data: {
            name: product.name,
            description: product.description,
            priceCents: product.priceCents,
            costCents: product.costCents,
            visibility: product.inventoryEnabled ? 'visible' : 'hidden',
            status: product.status,
          },
        }),
      })
      if (!res.ok) throw new Error(`persist ${res.status}`)
      await loadProducts()
    } catch (error) {
      console.error('[store] persist product failed', error)
    } finally {
      setSavingProductId(null)
    }
  }

  function previewDescription(text: string, maxWords = 8): string {
    const words = text.trim().split(/\s+/)
    if (words.length <= maxWords) return text
    return `${words.slice(0, maxWords).join(' ')}…`
  }

  function toggleProductSelection(id: string, state?: CheckedState) {
    setSelectedProductIds((prev) => {
      const next = new Set(prev)
      const shouldSelect = state === undefined ? !next.has(id) : state === true || state === 'indeterminate'
      if (shouldSelect) next.add(id)
      else next.delete(id)
      return next
    })
  }

  function handleSelectAll(state: CheckedState) {
    if (state === true) {
      setSelectedProductIds(new Set(products.map((p) => p.id)))
    } else {
      setSelectedProductIds(new Set())
    }
  }

  const allSelected = products.length > 0 && selectedProductIds.size === products.length
  const someSelected = selectedProductIds.size > 0 && !allSelected
  const selectAllState: CheckedState = allSelected ? true : someSelected ? 'indeterminate' : false

  async function toggleInventory(id: string) {
    const product = products.find((p) => p.id === id)
    if (!product) return
    updateProduct(id, (p) => ({ ...p, inventoryEnabled: !p.inventoryEnabled }))
    await persistProduct({ ...product, inventoryEnabled: !product.inventoryEnabled })
  }

  function handleDragEnter(e: React.DragEvent<HTMLDivElement>) {
    if (!e.dataTransfer?.items) return
    if (Array.from(e.dataTransfer.items).some((item) => item.kind === 'file')) {
      e.preventDefault()
      setIsDragging(true)
    }
  }

  function handleDragOver(e: React.DragEvent<HTMLDivElement>) {
    if (isDragging) e.preventDefault()
  }

  function handleDragLeave(e: React.DragEvent<HTMLDivElement>) {
    if (e.currentTarget.contains(e.relatedTarget as Node)) return
    setIsDragging(false)
  }

  function handleDrop(e: React.DragEvent<HTMLDivElement>) {
    if (!isDragging) return
    e.preventDefault()
    setIsDragging(false)
    if (e.dataTransfer?.files && e.dataTransfer.files.length > 0) {
      handleFiles(e.dataTransfer.files)
    }
  }

  return (
    <>
      {!draftModalOpen && draftError && (
        <div className="fixed left-1/2 top-4 z-40 -translate-x-1/2 rounded-lg bg-warning px-4 py-2 text-sm font-medium text-black shadow-lg">
          {draftError}
        </div>
      )}
      <UploadProductModal
        open={draftModalOpen && Boolean(activeDraftViewModel)}
        draft={activeDraftViewModel}
        saving={draftSaving}
        error={draftError}
        onClose={handleDraftModalClose}
        onDiscard={handleDraftModalClose}
        onSave={handleDraftSave}
        onChange={(update) => {
          const next: Partial<DraftProductState> = {}
          if (update.name !== undefined) next.name = update.name
          if (update.description !== undefined) next.description = update.description
          if (update.priceCents !== undefined) next.priceCents = update.priceCents
          if (update.costCents !== undefined) next.costCents = update.costCents
          handleDraftChange(next)
        }}
      />
      <main className="flex min-h-screen gap-4 bg-obsidian p-4 text-textPrimary">
        <div className="relative h-[calc(100vh-2rem)]">
          <LeftRail showOperator={showOperator} />
        </div>
        <div className="flex flex-1 min-w-0 gap-4">
          <div
          className={`panel relative flex min-w-0 flex-1 flex-col gap-6 overflow-hidden h-[calc(100vh-2rem)] max-h-[calc(100vh-2rem)] p-5 ${isDragging ? 'ring-2 ring-teal/60' : ''}`}
          onDragEnter={handleDragEnter}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
        >
          {isDragging && (
            <>
              <div className="pointer-events-none absolute inset-0 z-10 rounded-lgx border-2 border-dashed border-teal/60" />
              <div className="pointer-events-none absolute inset-0 z-10 rounded-lgx bg-teal/5 backdrop-blur-sm" />
              <div className="pointer-events-none absolute inset-0 z-20 flex items-center justify-center text-sm font-medium text-teal">
                Drop STL, OBJ, GLB, or GLTF
              </div>
            </>
          )}
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div className="space-y-1">
              <span className="text-xs uppercase tracking-wide text-teal">My store</span>
              <h1 className="text-2xl font-semibold text-white">Product inventory</h1>
              <p className="text-sm text-textMuted">
                Drop in STLs or GLBs to generate product listings automatically. We&apos;ll repair the mesh, slice it for pricing, and draft copy you can approve with a click.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <label className="flex cursor-pointer items-center justify-center rounded-mdx bg-gradient-to-r from-teal via-teal/90 to-teal/80 px-4 py-2 text-sm font-medium text-black shadow-[0_8px_16px_rgba(46,230,214,0.2)] transition hover:brightness-110">
                <input
                  type="file"
                  multiple
                  accept=".stl,.obj,.glb,.gltf"
                  className="hidden"
                  onChange={(event) => {
                    const files = event.target.files
                    if (files && files.length > 0) {
                      handleFiles(files)
                    }
                    event.target.value = ''
                  }}
                />
                Upload models
              </label>
            </div>
          </div>
          <div className="flex items-center justify-between text-xs text-textMuted/80">
            <span>
              {selectedProductIds.size} selected • {loading ? 'Loading…' : `${products.length} total`}
            </span>
            {someSelected && <span className="text-xs text-teal">Bulk actions coming soon</span>}
          </div>
          <div className="flex-1 overflow-hidden">
            <div className="h-full overflow-auto rounded-2xl border border-white/10 bg-white/[0.035] shadow-[0_18px_40px_-30px_rgba(0,0,0,0.8)]">
              <div className="sticky top-0 z-10 grid grid-cols-[56px,minmax(300px,1.6fr),minmax(160px,0.75fr),minmax(160px,0.75fr),minmax(220px,0.95fr),minmax(130px,0.55fr)] items-center gap-7 border-b border-white/10 bg-black/40 px-7 py-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-textMuted">
                <div className="flex items-center justify-center">
                  <HoloCheckbox
                    checked={selectAllState}
                    onCheckedChange={handleSelectAll}
                    ariaLabel="Select all products"
                  />
                </div>
                <div>Product</div>
                <div className="text-right pr-6">Pricing</div>
                <div className="text-right pr-4">Updated</div>
                <div className="text-right pr-6">Channels</div>
                <div className="text-right pr-4">Status</div>
              </div>
              {products.map((product) => {
                const margin = product.priceCents - product.costCents
                const marginPct = product.priceCents > 0 ? Math.min(Math.max((margin / product.priceCents) * 100, 0), 100) : 0
                return (
                  <div
                    key={product.id}
                    className={`group grid grid-cols-[56px,minmax(300px,1.6fr),minmax(160px,0.75fr),minmax(160px,0.75fr),minmax(220px,0.95fr),minmax(130px,0.55fr)] items-center gap-7 border-b border-white/5 px-7 py-4 transition hover:bg-white/[0.045] ${selectedProductId === product.id ? 'border-teal/40 bg-white/[0.07]' : ''}`}
                    onClick={() => setSelectedProductId(product.id)}
                  >
                    <div
                      className="flex items-start justify-center"
                      onClick={(event) => event.stopPropagation()}
                    >
                      <HoloCheckbox
                        checked={selectedProductIds.has(product.id)}
                        onCheckedChange={(state) => {
                          toggleProductSelection(product.id, state)
                        }}
                        ariaLabel={`Select ${product.name}`}
                      />
                    </div>
                    <div className="flex min-w-0 items-center gap-4">
                      <div className="relative h-16 w-16 flex-shrink-0 overflow-hidden rounded-lg border border-white/10 bg-black/40">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={product.thumbnailUrl || '/placeholder.png'} alt="Thumb" className="h-full w-full object-cover" />
                      </div>
                      <div className="min-w-0 space-y-1">
                        <div className="flex items-center gap-2">
                          <span className="truncate text-sm font-medium text-white">{product.name}</span>
                          {product.autogenerated && (
                            <span className="rounded-full border border-white/10 px-2 text-[10px] uppercase tracking-widest text-textMuted">
                              Draft
                            </span>
                          )}
                        </div>
                        <div className="truncate text-xs text-textMuted">{previewDescription(product.description)}</div>
                        <div className="text-[11px] uppercase tracking-[0.18em] text-textMuted/70">{product.id}</div>
                      </div>
                    </div>
                    <div className="flex flex-col items-end gap-1 pr-6 text-right">
                      <span className="text-sm font-semibold text-white">{formatCurrency(product.priceCents)}</span>
                      <span className="text-xs text-textMuted">Cost {formatCurrency(product.costCents)} · {Math.round(marginPct)}%</span>
                      <div className="relative h-1.5 w-28 overflow-hidden rounded-full bg-white/10">
                        <div className="absolute left-0 top-0 h-full rounded-full bg-teal" style={{ width: `${Math.min(Math.max(marginPct, 0), 100)}%` }} />
                      </div>
                    </div>
                    <div className="text-right pr-4 text-sm text-textMuted">
                      <div className="text-xs text-textMuted/60">Last updated</div>
                      <div className="text-sm text-white">{formatDate(product.updatedAt)}</div>
                    </div>
                    <div className="flex items-center justify-end gap-2 pr-6">
                      {product.channels.map((channel) => (
                        <span
                          key={`${product.id}-${channel.name}`}
                          className={`inline-flex items-center gap-2 rounded-full border border-white/10 px-2 py-0.5 ${channelChip(channel.status)}`}
                        >
                          <span className={`h-1.5 w-1.5 rounded-full ${statusDot(channel.status)}`} />
                          {channel.name}
                        </span>
                      ))}
                      {product.channels.length === 0 && <span className="text-textMuted/50">Not connected</span>}
                    </div>
                    <div className="flex items-center justify-end gap-3 pr-4 text-xs text-textMuted">
                      <span className="text-[11px] text-textMuted/60">{product.inventoryEnabled ? 'Visible' : 'Hidden'}</span>
                      <button
                        type="button"
                        className={`inline-flex h-5 w-10 items-center rounded-full border border-white/15 px-1 transition ${
                          product.inventoryEnabled ? 'bg-teal/40' : 'bg-white/5'
                        }`}
                        onClick={(event) => {
                          event.stopPropagation()
                          void toggleInventory(product.id)
                        }}
                        aria-label={product.inventoryEnabled ? 'Disable product' : 'Enable product'}
                      >
                        <span
                          className={`h-3.5 w-3.5 rounded-full bg-white transition-transform ${
                            product.inventoryEnabled ? 'translate-x-5' : 'translate-x-0'
                          }`}
                        />
                      </button>
                    </div>
                  </div>
                )
              })}
              {products.length === 0 && !loading && (
                <div className="px-7 py-12 text-center text-sm text-textMuted">No products yet. Upload a model to get started.</div>
              )}
            </div>
          </div>
        </div>

        <aside className="flex w-[400px] flex-shrink-0 flex-col h-[calc(100vh-2rem)] max-h-[calc(100vh-2rem)] overflow-hidden">
          {selectedProduct ? (
            <div className="panel relative flex h-full flex-col overflow-hidden px-5 pb-5 pt-6">
              <div className="flex items-center justify-between text-[11px] uppercase tracking-[0.24em] text-teal/80">
                <span>Product details</span>
                {previewImages.length > 1 && (
                  <span className="text-textMuted/60">{safePreviewIndex + 1} / {previewImages.length}</span>
                )}
              </div>
              <div className="mt-4 flex flex-1 flex-col gap-6 overflow-hidden">
                <div className="space-y-4">
                  <div className="relative aspect-square w-full overflow-hidden rounded-xl bg-gradient-to-b from-white/10/[0.04] to-black/30">
                    {previewImageUrl ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={previewImageUrl} alt="Selected product view" className="absolute inset-0 h-full w-full object-cover" />
                    ) : (
                      <div className="absolute inset-0 flex items-center justify-center text-xs text-textMuted">
                        Add product images to preview them here.
                      </div>
                    )}
                  </div>
                  {previewImages.length > 0 && (
                    <div className="flex items-center justify-start gap-3 overflow-x-auto pb-1">
                      {previewImages.map((url, idx) => {
                        const isActive = idx === safePreviewIndex
                        return (
                          <button
                            type="button"
                            key={`${selectedProduct.id}-concept-${idx}`}
                            onClick={() => setPreviewIndexByProduct((prev) => ({ ...prev, [selectedProduct.id]: idx }))}
                            className={`relative inline-flex h-14 w-14 flex-shrink-0 items-center justify-center overflow-hidden rounded-md border border-white/10 transition focus:outline-none ${
                              isActive ? 'border-teal/70 shadow-[0_0_0_2px_rgba(46,230,214,0.25)]' : 'hover:border-teal/40'
                            }`}
                            aria-pressed={isActive}
                            aria-label={`Select product image ${idx + 1}`}
                          >
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img src={url} alt="Product thumbnail" className="h-full w-full object-cover" />
                          </button>
                        )
                      })}
                    </div>
                  )}
                  <input
                    type="text"
                    value={selectedProduct.name}
                    onChange={(event) => {
                      const next = event.target.value
                      updateProduct(selectedProduct.id, (p) => ({ ...p, name: next }))
                    }}
                    className="w-full border-b border-white/10 bg-transparent pb-2 text-xl font-medium tracking-tight text-white placeholder:text-textMuted focus:border-teal/70 focus:outline-none"
                  />
                  <textarea
                    className="h-28 w-full resize-none rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm leading-relaxed text-textPrimary backdrop-blur-sm transition focus:border-teal/70 focus:outline-none"
                    value={selectedProduct.description}
                    onChange={(event) => {
                      const next = event.target.value
                      updateProduct(selectedProduct.id, (p) => ({ ...p, description: next }))
                    }}
                  />
                </div>
                <div className="space-y-4 text-sm">
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="text-lg font-semibold text-white">{formatCurrency(selectedProduct.priceCents)}</div>
                      <div className="text-xs text-textMuted">
                        Margin: {formatCurrency(Math.max(selectedProduct.priceCents - selectedProduct.costCents, 0))}
                      </div>
                    </div>
                    <button
                      type="button"
                      className="inline-flex items-center rounded-full border border-white/15 px-3 py-1 text-[11px] uppercase tracking-wide text-textMuted transition hover:border-teal/60 hover:text-white"
                      onClick={() => void persistProduct(selectedProduct)}
                    >
                      Sync
                    </button>
                  </div>
                  <div className="h-px bg-white/10" />
                  <div className="space-y-3 text-xs">
                    {selectedProduct.channels.map((channel) => (
                      <div key={channel.name} className="flex items-center justify-between gap-3 border-b border-white/10 pb-3 last:border-b-0 last:pb-0">
                        <div className="flex items-center gap-3">
                          <div
                            className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-semibold ${channelColor(channel.name)}`}
                          >
                            {channelInitials(channel.name)}
                          </div>
                          <div>
                            <div className="text-sm text-white">{channel.name}</div>
                            <div className="flex items-center gap-2 text-[11px] text-textMuted">
                              <span className={`inline-flex h-1.5 w-1.5 rounded-full ${statusDot(channel.status)}`} />
                              {channel.status === 'connected'
                                ? 'Ready to publish'
                                : channel.status === 'pending'
                                ? 'Syncing'
                                : 'Not connected'}
                            </div>
                          </div>
                        </div>
                        <button
                          type="button"
                          className="text-[11px] uppercase tracking-wide text-textMuted transition hover:text-teal"
                        >
                          Manage
                        </button>
                      </div>
                    ))}
                    {selectedProduct.channels.length === 0 && (
                      <div className="text-xs text-textMuted">No channels linked yet.</div>
                    )}
                    <button
                      type="button"
                      className="text-left text-[11px] uppercase tracking-wide text-textMuted transition hover:text-teal"
                    >
                      + Add channel
                    </button>
                  </div>
                </div>
              </div>
              <div className="mt-auto flex flex-col gap-2 border-t border-white/10 pt-5">
                <button
                  className="w-full rounded-lg bg-teal px-3 py-2 text-sm font-medium text-black hover:brightness-110 disabled:opacity-60"
                  type="button"
                  disabled={savingProductId === selectedProduct.id}
                  onClick={() => void persistProduct(selectedProduct)}
                >
                  {savingProductId === selectedProduct.id ? 'Saving…' : 'Save changes'}
                </button>
                <button className="w-full rounded-lg bg-white/5 px-3 py-2 text-sm text-textMuted transition hover:bg-white/10 hover:text-white" type="button">
                  View fulfillment timeline
                </button>
              </div>
            </div>
          ) : (
            <div className="panel h-full p-5 text-sm text-textMuted">Select a product to see details.</div>
          )}
        </aside>
      </div>
      </main>
    </>
  )
}
